# Generated by Django 4.2.6 on 2023-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0003_alter_organization_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="events",
            name="check_quantity_clients",
        ),
        migrations.RemoveConstraint(
            model_name="events",
            name="check_limit_clients",
        ),
        migrations.RemoveConstraint(
            model_name="recordings",
            name="unique_recording_customer",
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                check=models.Q(("hobby__in", ["SP", "TR", "ED", "SC", "SN"])),
                name="check_hobby_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity_clients__lte", models.F("limit_clients"))),
                name="check_quantity_clients_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("limit_clients__gt", 0)),
                name="check_limit_clients_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("status_tariff__in", ["PAID", "FREE"])),
                name="check_status_tariff_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("status_opening__in", ["OPEN", "CLOSE"])),
                name="check_status_opening_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="check_time_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="historyrecordings",
            constraint=models.CheckConstraint(
                check=models.Q(("status_recording__in", ["PAID", "CANC"])),
                name="check_status_recording",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                check=models.Q(("activity__in", ["SP", "TR", "ED", "SC", "SN"])),
                name="check_activity_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordings",
            constraint=models.UniqueConstraint(
                fields=("event", "customer"), name="unique_recordings_customer"
            ),
        ),
    ]
