# Generated by Django 4.2.6 on 2023-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0004_remove_events_check_quantity_clients_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="events",
            name="check_time_events",
        ),
        migrations.AddField(
            model_name="events",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="events",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
