# Generated by Django 4.2.6 on 2023-10-18 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0005_remove_events_check_time_events_events_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
