# Generated by Django 4.2.6 on 2023-10-18 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0006_alter_events_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="date",
            new_name="date_event",
        ),
    ]
