# Generated by Django 4.2.6 on 2023-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0007_rename_date_events_date_event"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="check_time_events",
            ),
        ),
    ]
