# Generated by Django 4.2.6 on 2023-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0010_alter_events_limit_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="quantity_clients",
            field=models.SmallIntegerField(default=0),
        ),
    ]
