# Generated by Django 4.2.6 on 2023-10-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import record.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0011_alter_events_quantity_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "hobby",
                    models.CharField(
                        choices=[
                            ("SP", "спорт"),
                            ("TR", "туризм"),
                            ("ED", "образование"),
                            ("SC", "наука"),
                            ("SN", "разное"),
                        ],
                        default="SN",
                        max_length=50,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        height_field=150,
                        null=True,
                        upload_to="photo_customer",
                        width_field=150,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("profile", models.JSONField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        height_field=150,
                        null=True,
                        upload_to="photo_employee",
                        width_field=150,
                    ),
                ),
            ],
            options={
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("SP", "спорт"),
                            ("TR", "туризм"),
                            ("ED", "образование"),
                            ("SC", "наука"),
                            ("SN", "разное"),
                        ],
                        default="SN",
                        max_length=50,
                    ),
                ),
                ("profile", models.JSONField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        height_field=150,
                        null=True,
                        upload_to="photo_organization",
                        width_field=150,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="user",
        ),
        migrations.AlterField(
            model_name="recordings",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="record.events",
            ),
        ),
        migrations.AlterModelTable(
            name="historyrecordings",
            table="history_recordings",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.AddField(
            model_name="employees",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="record.organizations",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="employee",
            field=models.ManyToManyField(to="record.employees"),
        ),
        migrations.AlterField(
            model_name="events",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="record.organizations",
            ),
        ),
        migrations.AlterField(
            model_name="recordings",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="record.customers",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.AddConstraint(
            model_name="organizations",
            constraint=models.CheckConstraint(
                check=models.Q(("activity__in", ["SP", "TR", "ED", "SC", "SN"])),
                name="check_activity_organizations",
            ),
        ),
        migrations.AddConstraint(
            model_name="customers",
            constraint=models.CheckConstraint(
                check=models.Q(("hobby__in", ["SP", "TR", "ED", "SC", "SN"])),
                name="check_hobby_customers",
            ),
        ),
    ]
