# Generated by Django 4.2.6 on 2023-10-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0012_customers_employees_organizations_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customers",
            name="check_hobby_customers",
        ),
        migrations.RemoveConstraint(
            model_name="organizations",
            name="check_activity_organizations",
        ),
        migrations.AlterField(
            model_name="customers",
            name="hobby",
            field=models.CharField(
                choices=[
                    ("SP", "спорт"),
                    ("TR", "туризм"),
                    ("ED", "образование"),
                    ("SC", "наука"),
                    ("ET", "развлечения"),
                    ("SN", "разное"),
                ],
                default="SN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="employee",
            field=models.ManyToManyField(related_name="events", to="record.employees"),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="activity",
            field=models.CharField(
                choices=[
                    ("SP", "спорт"),
                    ("TR", "туризм"),
                    ("ED", "образование"),
                    ("SC", "наука"),
                    ("ET", "развлечения"),
                    ("SN", "разное"),
                ],
                default="SN",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="customers",
            constraint=models.CheckConstraint(
                check=models.Q(("hobby__in", ["SP", "TR", "ED", "SC", "ET", "SN"])),
                name="check_hobby_customers",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizations",
            constraint=models.CheckConstraint(
                check=models.Q(("activity__in", ["SP", "TR", "ED", "SC", "ET", "SN"])),
                name="check_activity_organizations",
            ),
        ),
    ]
