# Generated by Django 4.2.6 on 2023-10-25 12:03

from django.db import migrations, models
import record.validators


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0013_remove_customers_check_hobby_customers_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customers",
            name="check_hobby_customers",
        ),
        migrations.RemoveConstraint(
            model_name="organizations",
            name="check_activity_organizations",
        ),
        migrations.AlterField(
            model_name="customers",
            name="hobby",
            field=models.CharField(
                choices=[
                    ("sport", "спорт"),
                    ("tourism", "туризм"),
                    ("education", "образование"),
                    ("science", "наука"),
                    ("entertainment", "развлечения"),
                    ("sundry", "разное"),
                ],
                default="sundry",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="activity",
            field=models.CharField(
                choices=[
                    ("sport", "спорт"),
                    ("tourism", "туризм"),
                    ("education", "образование"),
                    ("science", "наука"),
                    ("entertainment", "развлечения"),
                    ("sundry", "разное"),
                ],
                default="sundry",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="customers",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "hobby__in",
                        [
                            "sport",
                            "tourism",
                            "education",
                            "science",
                            "entertainment",
                            "sundry",
                        ],
                    )
                ),
                name="check_hobby_customers",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizations",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "activity__in",
                        [
                            "sport",
                            "tourism",
                            "education",
                            "science",
                            "entertainment",
                            "sundry",
                        ],
                    )
                ),
                name="check_activity_organizations",
            ),
        ),
    ]
