# Generated by Django 4.2.6 on 2023-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0017_remove_customers_check_hobby_customers_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organizations",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "activity__in",
                        [
                            "sport",
                            "tourism",
                            "education",
                            "science",
                            "entertainment",
                            "sundry",
                        ],
                    )
                ),
                name="check_activity_organizations",
            ),
        ),
    ]
