# Generated by Django 4.2.6 on 2023-10-25 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0018_organizations_check_activity_organizations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizations",
            name="check_activity_organizations",
        ),
    ]
