# Generated by Django 4.2.6 on 2023-10-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0020_organizations_check_activity_organizations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customers",
            name="check_hobby_customers",
        ),
        migrations.RemoveConstraint(
            model_name="organizations",
            name="check_activity_organizations",
        ),
        migrations.AlterField(
            model_name="events",
            name="status_opening",
            field=models.CharField(
                choices=[("OPEN", "открытые"), ("CLOSE", "закрытые")],
                default="OPEN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="status_tariff",
            field=models.CharField(
                choices=[("PAID", "платные"), ("FREE", "бесплатные")], max_length=4
            ),
        ),
    ]
