# Generated by Django 4.2.6 on 2023-10-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0021_remove_customers_check_hobby_customers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activitys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("sport", "спорт"),
                            ("tourism", "туризм"),
                            ("education", "образование"),
                            ("science", "наука"),
                            ("entertainment", "развлечения"),
                            ("sundry", "разное"),
                        ],
                        default="sundry",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "activitys",
            },
        ),
        migrations.RemoveField(
            model_name="organizations",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="customers",
            name="hobby",
        ),
        migrations.AddConstraint(
            model_name="activitys",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "name__in",
                        [
                            "sport",
                            "tourism",
                            "education",
                            "science",
                            "entertainment",
                            "sundry",
                        ],
                    )
                ),
                name="check_activitys",
            ),
        ),
        migrations.AddField(
            model_name="organizations",
            name="activitys",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="record.activitys",
            ),
        ),
        migrations.AddField(
            model_name="customers",
            name="hobby",
            field=models.ManyToManyField(
                related_name="customers", to="record.activitys"
            ),
        ),
    ]
