# Generated by Django 4.2.6 on 2023-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0022_activitys_remove_organizations_activity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="events",
            name="check_status_tariff_events",
        ),
        migrations.RemoveConstraint(
            model_name="events",
            name="check_status_opening_events",
        ),
        migrations.RemoveConstraint(
            model_name="historyrecordings",
            name="check_status_recording",
        ),
        migrations.AlterField(
            model_name="historyrecordings",
            name="status_recording",
            field=models.CharField(
                choices=[("paid", "оплачено"), ("canc", "отменено")], max_length=4
            ),
        ),
        migrations.AddConstraint(
            model_name="historyrecordings",
            constraint=models.CheckConstraint(
                check=models.Q(("status_recording__in", ["paid", "canc"])),
                name="check_status_recording",
            ),
        ),
    ]
