# Generated by Django 4.2.6 on 2023-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0024_alter_events_status_opening_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("status_tariff__in", ["paid", "free"])),
                name="check_status_tariff_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(
                check=models.Q(("status_opening__in", ["open", "close"])),
                name="check_status_opening_events",
            ),
        ),
    ]
