# Generated by Django 4.2.6 on 2023-11-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0025_events_check_status_tariff_events_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customers",
            name="hobby",
        ),
        migrations.AlterField(
            model_name="activitys",
            name="name",
            field=models.CharField(
                choices=[
                    ("sport", "спорт"),
                    ("tourism", "туризм"),
                    ("education", "образование"),
                    ("science", "наука"),
                    ("entertainment", "развлечение"),
                    ("sundry", "разное"),
                ],
                default="sundry",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="status_opening",
            field=models.CharField(
                choices=[("open", "открытый"), ("close", "закрытый")],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="status_tariff",
            field=models.CharField(
                choices=[("paid", "платный"), ("free", "бесплатный")], max_length=4
            ),
        ),
    ]
