# Generated by Django 4.2.6 on 2023-11-15 17:35

from django.db import migrations, models
import record.validators


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0027_employees_date_joined_organizations_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
