# Generated by Django 4.2.6 on 2023-11-16 07:42

import datetime
from django.db import migrations, models
import record.validators


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0028_alter_customers_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 16, 7, 42, 28, 820493, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="phone_number",
            field=models.CharField(
                default="87648731212",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="phone_number",
            field=models.CharField(
                default="87648731212",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="phone_number",
            field=models.CharField(
                default="87648731212",
                max_length=20,
                unique=True,
            ),
        ),
    ]
