# Generated by Django 4.2.6 on 2023-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0030_alter_customers_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="phone_number",
            field=models.CharField(
                error_messages={"unique": "такой номер телефона уже зарегистрирован"},
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="phone_number",
            field=models.CharField(
                error_messages={"unique": "такой номер телефона уже зарегистрирован"},
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="phone_number",
            field=models.CharField(
                error_messages={"unique": "такой номер телефона уже зарегистрирован"},
                max_length=20,
                unique=True,
            ),
        ),
    ]
