# Generated by Django 4.2.6 on 2023-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0031_alter_customers_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="birth_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "такой номер телефона уже зарегистрирован"},
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "такой email адрес уже зарегистрирован"},
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "такой номер телефона уже зарегистрирован"},
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "такой номер телефона уже зарегистрирован"},
                max_length=20,
                unique=True,
            ),
        ),
    ]
